### ISSUE TITLE
Choose latest android target by default

### ISSUE THREAD

**Issue by aaccurso** [tylerbuchea/cordova-android-crosswalk#10]
Currently if no target is passed the tool defaults to the first target listed by `android list`.
We should default to the latest installed target, don't you think?

**Comment by tylerbuchea** [comment]
Right the targets are listed in reverse chron order that was my bad. I'll work on this this week `android list target -c` gives a nice compact list. Then we could just grab the last "android-*" in the list.

**Comment by aaccurso** [comment]
Sounds great!

**Comment by tylerbuchea** [comment]
Okay just added the new functionality. I incremented to 0.2.0, because this fix changes the api in a way that could mess with peoples automation. This is the right thing to do if we pretend people other than me and you are actually using this :p I'm closing the issue.

**Comment by aaccurso** [comment]
I agree, new doc looks great!
