### ISSUE TITLE
Missing step for Crosswalk upgrade?

### ISSUE THREAD

**Issue by aaccurso** [tylerbuchea/cordova-android-crosswalk#13]
@tylerbuchea: In the Crosswalk documentation's [Upgrade using the command line tools](https://crosswalk-project.org/documentation/cordova/migrate_an_application.html#Upgrade-using-the-command-line-tools) there is a step 7 that I believe it's not being done by the tool:

#### go to the platforms/android directory
`cd ..`
#### remove the files from the previous Cordova build
`rm -Rf ant-gen`
`rm -Rf ant-build`

**This is the crucial step: you need Cordova to regenerate various libraries and assets which make reference to Crosswalk. However, Cordova assumes that the files in platforms/android/CordovaLib don't change, and won't automatically refresh them, which is why you must manually remove them here.**

**Comment by tylerbuchea** [comment]
Wow, good find! I can't believe I missed that. I've been wanting to clean up the `buildFinal` anyways so this will be the perfect excuse. I should have it patched up before the day closes.

**Comment by aaccurso** [comment]
Sounds great :smile:

**Comment by tylerbuchea** [comment]
Okay just fixed the issue. That was a huge oversight on my part. Thanks again for all the help it's awesome to have another set of eyes. This is shaping up to be a very nice tool.

**Comment by aaccurso** [comment]
Happy to contribute!
