### ISSUE TITLE
Not working on windows 8

### ISSUE THREAD

**Issue by andr3medeiros** [tylerbuchea/cordova-android-crosswalk#14]
I didn't have the chance to teste on another win versions, so sory for that.

I have a cordova project with platform android added and running. I "npm install -g cordova-android-crosswalk" and then, at the root folder of the project I ran "cordova-android-crosswalk" and got:

"Incorrect syntax:
type platforms/android/cordova/version' "

The error occours at line 125 of the file C:\Users\MY_PROFILE\AppData\Roaming\npm\node_modules\cordova-android-crosswalk\bin\cordova-android-crosswalk:

checkCordovaVersion: function() {
var printCmd = Runtime.isWin ? 'type' : 'cat';
    exec(printCmd + ' platforms/android/cordova/version')
...

 The reason is "type" command does not accept relative path to "pathname" arg.

So I changed by:

var cmd = Runtime.isWin ? 'cd platforms/android/cordova & type version' : 'cat platforms/android/cordova/version';
    exec(cmd)
...

And it woked.

Hope it helps.

**Comment by tylerbuchea** [comment]
Hey I just pushed the fix. Thanks for the update I don't have a Windows machine to try this stuff out on. Let me know if everything works fine I'm closing the issue for now.
