### ISSUE TITLE
Enhance: Use symbolic links instead of replacing libraries

### ISSUE THREAD

**Issue by aaccurso** [tylerbuchea/cordova-android-crosswalk#15]
After unzipping crosswalk it would be better to create a symbolic link in /CordovaLib to the unzipped /framework directory instead of removing and copying all the files.
I'll try to implement this today and send a PR.

**Comment by aaccurso** [comment]
This is not possible since cordova actually generates files in this directory.

**Comment by tylerbuchea** [comment]
Bummer, it was a cool idea though.
