### ISSUE TITLE
Hangs after adding AndroidManifest.xml permissions

### ISSUE THREAD

**Issue by i11ume** [tylerbuchea/cordova-android-crosswalk#16]
After `Added AndroidManifest.xml permissions` terminal just hangs and doesn't continue. This is on a fresh version of cordova 3.6.3

**Comment by tylerbuchea** [comment]
The last step does take some time maybe try running it for a bit longer and let me know if you at least get an error I can work with.

I'll still try and reproduce this. What OS are you running? What versions of Android SDK and Ant? Also is your global Cordova 3.6.3 or just the Android platform you added.

**Comment by tylerbuchea** [comment]
Okay I am closing the issue. If you have more details for me please open a new issue. If it was an error on your part I'd still like to know so I don't have to worry about this bug.

**Comment by opula** [comment]
I got this same issue while while trying to use iojs.  Switched back to 0.10.38 and it worked fine for me.

**Comment by sommerper** [comment]
@opula what did you switch the version on?

I also have this problem on OS X using cordova 6.1.1 after installing android api 19 and typing `cordova platform add android@3.6.3`

I get the same when using -f and android@5.1.1

**Comment by opula** [comment]
Once the cordova / crosswalk official implementation happened, I switched over to that.  It hasn't given me issue since.

I'm using node v4.2.1 & cordova v5.3.3

**Comment by sommerper** [comment]
@opula ah ok! I thought this was the version to use. Can you link me towards the official solution?

**Comment by opula** [comment]
Np: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

**Comment by tylerthebuildor** [comment]
I've deprecated this project since the official plugin was released @opula has the right idea. I state this in the README.
