### ISSUE TITLE
Compatibility with cordova-android@3.6.4

### ISSUE THREAD

**Issue by jbuck** [tylerbuchea/cordova-android-crosswalk#17]
Hi there! Thanks for writing this tool and saving me a bunch of time :)

After running the command `$ cordova-android-crosswalk --release stable --target android-19` I received the following message:

```
Crosswalk stable requires the android platform v3.6.3!
First remove your current android platform "cordova platform remove android"
Then add it back while specificying the version "cordova platform add android@3.6.3"
```

It looks like cordova-android@3.6.4 was released shortly after v3.6.3, with some small bug fixes. In my manual testing v3.6.4 was compatible with crosswalk@10.39.235.15. Would it be possible to add support for cordova-android@3.6.4? Maybe using some sort of semver comparison?

**Comment by tylerbuchea** [comment]
Very cool, thanks for the tip it's hard constantly keeping up to date with the versions and their compatibility. I believe you but I'll have to test it out myself first. Give me a couple days and I'll push an update.

I was thinking there must be later versions of Cordova that work with Crosswalk. Did you try any other versions out that I could look into?
Thanks again jbuck!

**Comment by tylerbuchea** [comment]
So I was thinking about it and instead of supporting officially unsupported versions. I added a force flag so you can run the tool against any platform version if you have the guts. Hope you like the solution I'm pretty dead set on it. Still love to hear your feedback though.

**Comment by jbuck** [comment]
Thanks for adding the `--force` flag, works well enough for me :+1:

I'm not sure what the best solution for the matrix of cordova-android, and crosswalk compatibility is. I asked about a support grid in IRC, but got no response. Maybe some sort of travis-ci job that pulls down each version and sees which ones pass, and which ones fail?
