### ISSUE TITLE
require android  version 3.5

### ISSUE THREAD

**Issue by ariesjia** [tylerbuchea/cordova-android-crosswalk#2]
My android version is  "3.5.0" , but still  let me update  android.
I saw the code is   
```javascript
var is35 = result.stdout.match(/w*3.5.1\w*/);
```

**Comment by tylerbuchea** [comment]
What is the terminal output for you? Also what version number do you have in the "./platforms/android/cordova/version" file?

**Comment by ariesjia** [comment]
termianl output :
`````
Found SDK target: android-19
Crosswalk requires Cordova 3.5!
Don't worry you can still use your current version of Cordova.
First remove your current android platform "cordova platform remove android"
Then add it back while specificying the version "cordova platform add android@3.5"
`````
the cordova version is 
`````
var VERSION = "3.5.0";
````

**Comment by tylerbuchea** [comment]
The issue should be fixed with the new update I just published. This was a bad assumption on my part and you know what they say about those :D Thanks a lot for the input ariesjia. I'm closing this for now if you continue to have the problem after the update by all means open up another ticket.
