### ISSUE TITLE
crosswalk 10 is compatible with cordova 3.6

### ISSUE THREAD

**Issue by edwinvanderham** [tylerbuchea/cordova-android-crosswalk#4]
The checkCordovaVersion checks if the cordova version being used is equal to 3.5. The very soon to become stable version 10 of crosswalk is compatible with cordova 3.6.3. Also, because of this check it is impossible to use a crosswalk version from the beta or canary channel with a newer cordova version

**Comment by tylerbuchea** [comment]
I'll dig into this one in the next couple days. I had no idea the post stable channels supported higher Cordova versions. Is there a link I can get from you where Cordova/Crosswalk compatibility versions are being tracked?

**Comment by edwinvanderham** [comment]
I don't think there is a single place where compatibility is tracked. I found this one in the release notes for crosswalk 10: https://crosswalk-project.org/blog/crosswalk-10-beta.html

**Comment by tylerbuchea** [comment]
I decided to wait until 10 was stable to fix this. It was just released so I added functionality so each release channel has its own platform dependency. I checked with the xwalk team and they are currently all dependent on 3.6.3 I'll try and keep it up to date. So if you hear about a dep change by all means open another ticket.

As of now everything is current.
