### ISSUE TITLE
Add support for multi-architecture

### ISSUE THREAD

**Issue by aaccurso** [tylerbuchea/cordova-android-crosswalk#6]
https://crosswalk-project.org/documentation/cordova/migrate_an_application.html#Multi-architecture-packages

**Comment by aaccurso** [comment]
Hi @tylerbuchea, how are you?
I'm currently working on a couple of cordova apps and I need to wrap them with xwalk and build them for x86 architecture.
This module rocks integrating cordova and xwalk, great work!
Now all I need is to be able to build for x86 :smiley: 
Would you consider merging this PR? Tell me if you want to change anything before.

**Comment by tylerbuchea** [comment]
Thanks for the contribution. I just tested it and everything seems to be solid. Really clean and I especially like the switch to spaces it makes those long lines much neater.

Only thing that was a little confusing was line #136 `Runtime.armReleaseChannel.replace(/arm/g,'x86')` if you could add a new variable to the `init` function like `Runtime.x86ReleaseChannel = Runtime.armReleaseChannel.replace(/arm/g,'x86');` then reference the new variable instead on line #136.

Do that and I'd be more than happy to merge your request. Again thanks a lot and I really appreciate the help.

**Comment by aaccurso** [comment]
Thanks to you, happy to contribute! I believe that was the fastest merge I got :smile:
